### PR TITLE
Support custom log function and add TypeScript definitions

### PR DESCRIPTION
**Pull request by aikoven**
Thank you for this library! I decided to move similar function outside of my projects but then I found your really nice implementation.

This PR add support for customizing logging. It also adds TypeScript definitions to allow TS users use this library right away without needing to install typings separately.

### CODE REVIEW

**Comment by bhstahl** [comment]
Cool! Thanks for this @aikoven.

 I wonder if `logRetries` no longer describes the option well. Perhaps just a callback that gets executed on retry (if it exists) would suffice:

```js
const options = {
    onRetry: (fn, retryCount, retryDelay) => console.log(`[auto-retry] [${fn.name} was rejected, retrying #${retryCount} after ${retryDelay}ms.`)
};

```

Also, before I merge would you also mind updating the documentation [in the README](https://github.com/bhstahl/auto-retry#autoretryfn-options--function), please?

**Comment by aikoven** [comment]
Sure!

Should I then leave both options, `logRetries` and `onRetry`? Having `onRetry: true` seems weird to me.

**Comment by bhstahl** [comment]
Yeah. I think all use cases can be simplified down to just the `onRetry` handler option, right?

**Comment by aikoven** [comment]
I guess `logRetries` is useful on its own, just to not to have to specify a long callback if the default behavior is enough for the user.

**Comment by aikoven** [comment]
I've reverted to the original `logRetries` logic and added `onRetry` option.

**Comment by bhstahl** [comment]
Looks good, thanks for adding this @aikoven! Merging + bumping now.

**Comment by aikoven** [comment]
Thanks!

**Pull request merged**
